### ISSUE TITLE
Won't build 

### ISSUE THREAD

**Issue by jacoby** [houseabsolute/Log-Dispatch#23]
Tried to install LWP::ConsoleLogger::Easy, which requires Log::Dispatch.  Running 5.24.0.

Attaching build.log, which can explain what went wrong better than I can.

[build.log.txt](https://github.com/houseabsolute/Log-Dispatch/files/511913/build.log.txt)

**Comment by autarch** [comment]
I'm guessing this is the same as https://rt.cpan.org/Ticket/Display.html?id=111143. If it's not, please submit a bug to RT. I should really disable issues on this repo. Thanks!
