### ISSUE TITLE
Log::Dispatch::File doesn't allow object filename

### ISSUE THREAD

**Issue by jberger** [houseabsolute/Log-Dispatch#36]
When the `filename` parameter passed to the Log::Dispatch::File constructor is an object that overloads stringification (as the new Mojo::File is) Params::Validate barfs rather than trying the stringification (or some other resolution method). 

This has become interesting to me since Mojo::Home has recently changed to generate Mojo::File path objects rather than strings (as of Mojolicious v7.15).

As discussed on IRC, @autarch mentioned that he was intending to change the validation layer from Params::Validate to Params::ValidationCompiler which could handle the overloaded object. I'm including this as a reminder. Meantime I can handle the stringification on my end, but this can serve as a tracking bug/reminder.

**Comment by autarch** [comment]
This is addressed in [the 2.59 trial release](https://metacpan.org/release/DROLSKY/Log-Dispatch-2.59-TRIAL)

**Comment by autarch** [comment]
Fixed in 2.60
