### ISSUE TITLE
Use octal notation for permissions in chmod error message

### ISSUE THREAD

**Issue by CarstenGrohmann** [houseabsolute/Log-Dispatch#43]
Hi Dave,

it would be great if you can improve the output of the chmod error in `_open_file()` from a decimal to an octal notation, because it would improve the readability significantly. 

**Current output:**
```
Cannot chmod web/logs/debug.log to 438: Operation not permitted at ../lib/cpan/Log/Dispatch/File.pm line 118.
```

**Improved output:**
```
Cannot chmod web/logs/debug.log to 0666: Operation not permitted at ../lib/cpan/Log/Dispatch/File.pm line 118.
```

Thank you,
Carsten

**Comment by autarch** [comment]
Agreed, a patch would be welcome. This should be a simply change to add some `sprintf`.
