### ISSUE TITLE
Fix breakage / syntax error in Log::Dispatch::ApacheLog

### ISSUE THREAD

**Issue by mschout** [houseabsolute/Log-Dispatch#48]
Log::Dispatch::ApacheLog no longer works.

Trying to add an ApacheLog a logger throws error:

    Undefined subroutine &Log::Dispatch::ApacheLog::validator called at /Users/mschout/Sync/gkgdrs/core/build/lib/perl5/site_perl/5.24.1/Log/Dispatch/ApacheLog.pm line 30.

Looking at the source code it seems that the sigil was missed on "validator".  PR coming to address this shortly.

**Comment by autarch** [comment]
Fixed in 2.66
