### ISSUE TITLE
Docs for log_and_die/log_and_croak seem incorrect.

### ISSUE THREAD

**Issue by hartzell** [houseabsolute/Log-Dispatch#51]
`log_and_die` and `log_and_croak` seem to be synonyms, the latter just calls the former ([here is the source](https://github.com/houseabsolute/Log-Dispatch/blob/master/lib/Log/Dispatch.pm#L181-L209)).

The documentation makes them sound as if they behave differently.

If I haven't misread the code, the docs should be updated (I can PR something if I'm not in the weeds).

**Comment by preaction** [comment]
Looks like this change caused it: https://github.com/houseabsolute/Log-Dispatch/commit/a2a216b19be0f07868034f0057f5f05b1f881908#diff-1b4cc254700c5bb75d866c985d9dd69e

So, you're right, they are the same now and the docs should be updated to reflect that.

**Comment by autarch** [comment]
Fixed in HEAD. Thanks!
