### ISSUE TITLE
Mail::Sender is deprecated and you should look to Email::Sender instead

### ISSUE THREAD

**Issue by ppisar** [houseabsolute/Log-Dispatch#64]
Testing 2.70 warns:

~~~~
t/basic.t .................................. Mail::Sender is deprecated and you should look to Email::Sender instead at /home/test/fedora/perl-Log-Dispatch/Log-Dispatch-2.70/blib/lib/Log/Dispatch/Email/MailSender.pm line 14.
~~~~

**Comment by autarch** [comment]
Sorry for the slow response. This isn't really an important warning in this context, though I would certainly encourage you _not_ to use that particular Log::Dispatch output class. I don't want to remove the output from the Log-Dispatch distro, and this warning doesn't cause any breakage, so I don't think there's anything to do here.
